### ISSUE TITLE
expandAllChildren

### ISSUE THREAD

**Issue by flysmallstrong** [embraceitmobile/animated_tree_view#40] opened 2024-01-04 01:16 UTC
Upon initial loading of the tree, it can be completely unfolded. But upon going back to the previous page and subsequently redirecting to this page, the tree does not unfold anew.

**Comment by vsaase** [comment] 2024-01-26 21:42
also the recursive argument is not used in the code for the function?

**Comment by vsaase** [comment] 2024-01-26 21:54
duplicate of #34

**Comment by jawwad-hassan89** [comment] 2024-08-10 08:39
hi @vsaase 
you can achieve this behaviour by using the expandAllChildren(Tree node, {bool recursive = false}) method introduced in the version 2.2.0. You can get the controller on the callback onTreeReady, and then call the expandAllChildren() method on the controller

**Closed** 2024-08-16 18:55 UTC
